spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        # 他大爷的，命名空间的这个也要加上，文档上完全没有啊，这个地方真的是血坑
        namespace: d359e765-907a-462d-86e9-4a1df7ed59d2
        # 组名也要加上啊
        group: EXAMPLE_GROUP
  application:
    name: example-provider
server:
  port: 8081

